# Generated by Django 5.0.3 on 2024-03-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tarefa', models.CharField(max_length=50)),
                ('materia_tarefa', models.CharField(blank=True, max_length=50, null=True)),
                ('anotacoes', models.CharField(blank=True, max_length=100, null=True)),
                ('data_entrega', models.DateField()),
            ],
        ),
    ]
