# Generated by Django 5.0.3 on 2024-03-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0002_rename_materia_tarefa_homework_materia_trabalho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='anotacoes',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Anotações'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='data_entrega',
            field=models.DateField(verbose_name='Data de entrega'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='materia_trabalho',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Matéria do trabalho'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='nome_trabalho',
            field=models.CharField(max_length=50, verbose_name='Nome do trabalho'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='tipo_trabalho',
            field=models.IntegerField(choices=[(1, 'Apresentação'), (2, 'Prova'), (3, 'Tarefa')], default=3, verbose_name='Tipo do trabalho'),
        ),
    ]
